#####################################################################################
#
#  https://docs.spring.io/spring-boot/docs/2.2.0.RELEASE/reference/html/appendix-application-properties.html
#
#####################################################################################

spring:
  main:
    lazy-initialization: true